const os = require('os')

console.log('Operating System Information:')
console.log('----------------------------------')
console.log('OS Architecture:', os.arch())
console.log('CPU Information:', os.cpus())
console.log('Free Memory:', os.freemem(), 'bytes')
console.log('Total Memory:', os.totalmem(), 'bytes')
console.log('Hostname:', os.hostname())
console.log('Platform:', os.platform())
console.log('OS Release:', os.release())
console.log('System Uptime:', os.uptime(), 'seconds')
console.log('Network Interfaces:', os.networkInterfaces())